# Generated by Django 5.1.6 on 2025-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_session_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
