# Generated by Django 5.1.6 on 2025-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_stripe_session_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет'), ('stripe', 'Stripe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
